from apps.scraper.manual.behance import Behance
from apps.scraper.manual.deviantart import DeviantArt
from apps.scraper.manual.dribble import Dribble
from apps.scraper.manual.github import Github
from apps.scraper.manual.lastfm import LastFM
from apps.scraper.manual.onlyfans import OnlyFans
from apps.scraper.manual.pornhub import Pornhub
from apps.scraper.manual.replit import Replit
from apps.scraper.manual.telegram import Telegram
